// Generated by scripts/build-pwa.cjs from the canonical local trip and quality modules.
(function(global){
'use strict';
const modules={
"miniprogram/utils/offline-trips.js":function(module,exports,require){
// Offline field trips never call wx.request, fetch, or a backend. Local storage is
// owned by the page, so this module can be tested with networking entirely absent.
const bundle = require("miniprogram/data/taiyuan-line-2-offline.js");

const MODE = 'offline-field-manual';
const DATA_VERSION = bundle.dataVersion;
const STORAGE_ADDRESS = 'offline://taiyuan-line-2';
const copy = (value) => JSON.parse(JSON.stringify(value));

function fail(code, message) {
  throw Object.assign(new Error(message), { code });
}

function getLines() { return copy(bundle.lines); }

function requireText(input, field) {
  if (typeof input[field] !== 'string' || !input[field].trim()) fail('INVALID_TRIP', '请选择有效线路、方向和站点');
  return input[field].trim();
}

function routeFor(input) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) fail('INVALID_TRIP', '行程信息格式无效');
  const line = bundle.lines.find((item) => item.id === requireText(input, 'lineId'));
  if (!line) fail('INVALID_LINE', '离线现场测试仅支持太原地铁 2 号线');
  const direction = line.directions.find((item) => item.id === requireText(input, 'directionId'));
  if (!direction) fail('INVALID_DIRECTION', '请选择有效方向');
  const fromId = requireText(input, 'fromStationId');
  const toId = requireText(input, 'toStationId');
  const from = direction.orderedStationIds.indexOf(fromId);
  const to = direction.orderedStationIds.indexOf(toId);
  if (from < 0 || to <= from) fail('INVALID_STATIONS', '目标站必须位于当前行车方向的上车站之后');
  const byId = new Map(line.stations.map((station) => [station.id, station]));
  const route = direction.orderedStationIds.slice(from, to + 1).map((id, index, ids) => {
    const station = byId.get(id);
    // secondsToNext belongs to the physical edge in the snapshot's forward order.
    // Reverse travel uses the next station's forward edge duration.
    const edge = direction.reverse ? byId.get(ids[index + 1]) : station;
    return { ...station, secondsToNext: index === ids.length - 1 ? 0 : edge.secondsToNext,
      minutesToNext: index === ids.length - 1 ? 0 : edge.minutesToNext };
  });
  return { line, direction: copy(direction), route };
}

function timestamp(now) {
  const value = typeof now === 'function' ? now() : now === undefined ? Date.now() : now;
  const date = value instanceof Date ? value : new Date(value);
  if (!Number.isFinite(date.getTime())) fail('INVALID_TIME', '本机时间无效，无法记录行程');
  return date.toISOString();
}

function view(trip) {
  const remaining = trip.route.length - trip.currentIndex - 1;
  const scheduledSecondsRemaining = trip.route.slice(trip.currentIndex, -1)
    .reduce((total, station) => total + station.secondsToNext, 0);
  return {
    ...trip,
    currentStation: { ...trip.route[trip.currentIndex] },
    stopsRemaining: remaining,
    status: remaining === 0 ? 'arrived' : 'active',
    shouldRemind: remaining <= trip.remindBefore,
    scheduledSecondsRemaining,
    scheduledMinutesRemaining: Math.round(scheduledSecondsRemaining / 60 * 10) / 10,
    // Deliberately no realtime ETA: this is just the sum of static edge durations.
    isRealtime: false,
    estimateMode: MODE,
    mode: MODE,
    locationAutoAdvance: false,
    coordinateVerificationStatus: 'pending-verification',
    confidence: 'manual',
    confidenceReason: '离线现场测试 / 人工进度；仅按人工经过车站更新，不代表真实列车位置'
  };
}

function createTrip(input, options = {}) {
  const { line, direction, route } = routeFor(input);
  const remindBefore = input.remindBefore === undefined ? 1 : input.remindBefore;
  if (!Number.isInteger(remindBefore) || remindBefore < 0 || remindBefore > 2) {
    fail('INVALID_REMINDER', '提醒站数只能是 0、1 或 2');
  }
  const createdAt = timestamp(options.now);
  const id = options.idFactory ? options.idFactory() : `offline-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 12)}`;
  if (typeof id !== 'string' || !id.trim() || id.length > 160) fail('INVALID_TRIP', '本机行程编号无效');
  return view({
    id, dataVersion: DATA_VERSION,
    cityId: bundle.city.id, lineId: line.id, lineName: line.name, lineColor: line.color,
    direction, fromStationId: route[0].id, toStationId: route[route.length - 1].id,
    remindBefore, route, currentIndex: 0, createdAt, updatedAt: createdAt
  });
}

function restoreTrip(saved) {
  if (!saved || typeof saved !== 'object' || Array.isArray(saved)) fail('INVALID_OFFLINE_TRIP', '本机离线行程记录不完整，请清除后重新开始');
  if (saved.mode !== MODE || saved.dataVersion !== DATA_VERSION) {
    fail('OFFLINE_DATA_VERSION_MISMATCH', '离线行程数据版本已变化，请清除旧记录后重新选择行程');
  }
  if (saved.locationAutoAdvance !== false || saved.isRealtime !== false) {
    fail('INVALID_OFFLINE_TRIP', '本机离线行程安全标记无效，请重新开始');
  }
  if (typeof saved.createdAt !== 'string' || typeof saved.updatedAt !== 'string'
    || !Number.isFinite(Date.parse(saved.createdAt)) || !Number.isFinite(Date.parse(saved.updatedAt))) {
    fail('INVALID_OFFLINE_TRIP', '本机离线行程时间记录无效，请重新开始');
  }
  if (typeof saved.id !== 'string' || !saved.id.trim() || saved.id.length > 160) {
    fail('INVALID_OFFLINE_TRIP', '本机离线行程编号无效，请重新开始');
  }
  const rebuilt = createTrip({
    lineId: saved.lineId, directionId: saved.direction?.id,
    fromStationId: saved.fromStationId, toStationId: saved.toStationId,
    remindBefore: saved.remindBefore
  }, { now: saved.createdAt, idFactory: () => saved.id });
  if (!Number.isInteger(saved.currentIndex) || saved.currentIndex < 0 || saved.currentIndex >= rebuilt.route.length
    || !Number.isInteger(saved.remindBefore)
    || !Array.isArray(saved.route) || saved.route.length !== rebuilt.route.length
    || saved.route.some((station, index) => !station || station.id !== rebuilt.route[index].id)) {
    fail('INVALID_OFFLINE_TRIP', '本机离线行程站序或进度无效，请重新开始');
  }
  // Saved names, durations, remaining stops, alerts and safety flags are never
  // trusted as authority; rederive all display fields from the packaged snapshot.
  return view({ ...rebuilt, currentIndex: saved.currentIndex, updatedAt: timestamp(saved.updatedAt) });
}

function validateTrip(saved) {
  try { restoreTrip(saved); return true; } catch (_) { return false; }
}

function advanceTrip(saved, expectedCurrentIndex, options = {}) {
  const trip = restoreTrip(saved);
  if (!Number.isInteger(expectedCurrentIndex)) fail('INVALID_PROGRESS_VERSION', '请提供有效的人工进度版本');
  if (expectedCurrentIndex !== trip.currentIndex) fail('TRIP_VERSION_CONFLICT', '行程进度已更新，请查看当前站后再操作');
  if (trip.status === 'arrived') return trip;
  return view({ ...trip, currentIndex: trip.currentIndex + 1, updatedAt: timestamp(options.now) });
}

module.exports = { MODE, DATA_VERSION, STORAGE_ADDRESS, getLines, createTrip, advanceTrip, restoreTrip, validateTrip };

},
"miniprogram/data/taiyuan-line-2-offline.js":function(module,exports,require){
// Generated by scripts/build-offline-data.cjs. Edit the JSON package, then rebuild.
module.exports = {
  "schemaVersion": 1,
  "dataVersion": "taiyuan-line-2-offline-2026-09-20-v1",
  "source": {
    "name": "太原地铁 2 号线本地站序与计划时间包",
    "mode": "offline-field-manual",
    "realtime": false,
    "file": "data/taiyuan-line-2.json",
    "upstreamUrl": "https://www.tymetro.ltd/api/lines",
    "upstreamUpdatedAt": "2025-05-23 18:07:47",
    "stationOrderCheckedOn": "2026-09-19",
    "packagedOn": "2026-09-20",
    "notice": "复用已校验站序、方向和静态计划站间秒数；计划时间不是实时 ETA，不表示现场运营时刻。未打包未核验坐标。"
  },
  "city": {
    "id": "taiyuan",
    "name": "太原",
    "operator": "太原轨道交通"
  },
  "lines": [
    {
      "id": "2",
      "name": "2号线",
      "color": "#e13a1b",
      "coordinateSystem": "unknown",
      "coordinateVerificationStatus": "pending-verification",
      "locationAutoAdvance": false,
      "realtime": false,
      "mode": "offline-field-manual",
      "directions": [
        {
          "id": "to-jiancaoping",
          "name": "尖草坪方向",
          "terminalStationId": "jiancaoping",
          "reverse": false,
          "orderedStationIds": [
            "xiqiao",
            "huazhangxijie",
            "tongdajie",
            "kangningjie",
            "dianzixijie",
            "jiajie",
            "longchenggongyuan",
            "longxingjie",
            "jinyangjie",
            "nanzhonghuan",
            "xuefujie",
            "changfengjie",
            "wangcunnanjie",
            "nanneihuan",
            "tiyuguan",
            "dananmen",
            "kaihuasijie",
            "fuxijie",
            "jihuying",
            "dabeimen",
            "shenglijie",
            "jianhe",
            "jiancaoping"
          ]
        },
        {
          "id": "to-xiqiao",
          "name": "西桥方向",
          "terminalStationId": "xiqiao",
          "reverse": true,
          "orderedStationIds": [
            "jiancaoping",
            "jianhe",
            "shenglijie",
            "dabeimen",
            "jihuying",
            "fuxijie",
            "kaihuasijie",
            "dananmen",
            "tiyuguan",
            "nanneihuan",
            "wangcunnanjie",
            "changfengjie",
            "xuefujie",
            "nanzhonghuan",
            "jinyangjie",
            "longxingjie",
            "longchenggongyuan",
            "jiajie",
            "dianzixijie",
            "kangningjie",
            "tongdajie",
            "huazhangxijie",
            "xiqiao"
          ]
        }
      ],
      "stations": [
        {
          "id": "xiqiao",
          "name": "西桥",
          "sequence": 1,
          "minutesToNext": 2.3,
          "secondsToNext": 138
        },
        {
          "id": "huazhangxijie",
          "name": "化章西街",
          "sequence": 2,
          "minutesToNext": 2.3,
          "secondsToNext": 138
        },
        {
          "id": "tongdajie",
          "name": "通达街",
          "sequence": 3,
          "minutesToNext": 2.3,
          "secondsToNext": 138
        },
        {
          "id": "kangningjie",
          "name": "康宁街",
          "sequence": 4,
          "minutesToNext": 2.1,
          "secondsToNext": 128
        },
        {
          "id": "dianzixijie",
          "name": "电子西街",
          "sequence": 5,
          "minutesToNext": 2.2,
          "secondsToNext": 132
        },
        {
          "id": "jiajie",
          "name": "嘉节",
          "sequence": 6,
          "minutesToNext": 1.9,
          "secondsToNext": 114
        },
        {
          "id": "longchenggongyuan",
          "name": "龙城公园",
          "sequence": 7,
          "minutesToNext": 1.9,
          "secondsToNext": 114
        },
        {
          "id": "longxingjie",
          "name": "龙兴街",
          "sequence": 8,
          "minutesToNext": 1.7,
          "secondsToNext": 102
        },
        {
          "id": "jinyangjie",
          "name": "晋阳街",
          "sequence": 9,
          "minutesToNext": 1.7,
          "secondsToNext": 102
        },
        {
          "id": "nanzhonghuan",
          "name": "南中环",
          "sequence": 10,
          "minutesToNext": 2.2,
          "secondsToNext": 132
        },
        {
          "id": "xuefujie",
          "name": "学府街",
          "sequence": 11,
          "minutesToNext": 2.1,
          "secondsToNext": 126
        },
        {
          "id": "changfengjie",
          "name": "长风街",
          "sequence": 12,
          "minutesToNext": 2.4,
          "secondsToNext": 144
        },
        {
          "id": "wangcunnanjie",
          "name": "王村南街",
          "sequence": 13,
          "minutesToNext": 1.8,
          "secondsToNext": 108
        },
        {
          "id": "nanneihuan",
          "name": "南内环",
          "sequence": 14,
          "minutesToNext": 1.9,
          "secondsToNext": 114
        },
        {
          "id": "tiyuguan",
          "name": "体育馆",
          "sequence": 15,
          "minutesToNext": 2.3,
          "secondsToNext": 138
        },
        {
          "id": "dananmen",
          "name": "大南门",
          "sequence": 16,
          "minutesToNext": 1.9,
          "secondsToNext": 114
        },
        {
          "id": "kaihuasijie",
          "name": "开化寺街",
          "sequence": 17,
          "minutesToNext": 1.8,
          "secondsToNext": 108
        },
        {
          "id": "fuxijie",
          "name": "府西街",
          "sequence": 18,
          "minutesToNext": 1.8,
          "secondsToNext": 108
        },
        {
          "id": "jihuying",
          "name": "缉虎营",
          "sequence": 19,
          "minutesToNext": 2.1,
          "secondsToNext": 126
        },
        {
          "id": "dabeimen",
          "name": "大北门",
          "sequence": 20,
          "minutesToNext": 2,
          "secondsToNext": 120
        },
        {
          "id": "shenglijie",
          "name": "胜利街",
          "sequence": 21,
          "minutesToNext": 2,
          "secondsToNext": 120
        },
        {
          "id": "jianhe",
          "name": "涧河",
          "sequence": 22,
          "minutesToNext": 2.1,
          "secondsToNext": 126
        },
        {
          "id": "jiancaoping",
          "name": "尖草坪",
          "sequence": 23,
          "minutesToNext": 0,
          "secondsToNext": 0
        }
      ]
    }
  ]
};

},
"miniprogram/utils/field-storage.js":function(module,exports,require){
const offline = require("miniprogram/utils/offline-trips.js");

const TRIP_KEY = 'daozhanla.offline-field-trip.v1';
const MODE_KEY = 'daozhanla.work-mode.v1';
const MAX_TRIP_AGE_MS = 24 * 60 * 60 * 1000;
const CLOCK_SKEW_MS = 5 * 60 * 1000;

function invalidTime(message, code = 'INVALID_OFFLINE_TRIP_TIME') {
  throw Object.assign(new Error(message), { code });
}

// The same recovery guard applies to a storage record and an in-memory trip
// returning from the background. Saving again never extends the creation TTL.
function validateRecoveryTrip(value, { now = Date.now(), savedAt } = {}) {
  const trip = offline.restoreTrip(value);
  const currentTime = typeof now === 'function' ? now() : now;
  const createdAt = Date.parse(trip.createdAt);
  const updatedAt = Date.parse(trip.updatedAt);
  if (typeof currentTime !== 'number' || !Number.isFinite(currentTime) || currentTime < 0
    || createdAt < 0 || updatedAt < createdAt) {
    invalidTime('本机离线行程时间记录无效，请确认手机时间后重新开始');
  }
  if (savedAt !== undefined && (typeof savedAt !== 'number' || !Number.isFinite(savedAt)
    || savedAt < updatedAt)) {
    invalidTime('本机离线行程保存时间无效，请确认手机时间后重新开始');
  }
  if (createdAt > currentTime + CLOCK_SKEW_MS || updatedAt > currentTime + CLOCK_SKEW_MS
    || (savedAt !== undefined && savedAt > currentTime + CLOCK_SKEW_MS)) {
    invalidTime('本机离线行程时间在未来，请确认手机时间后重新开始');
  }
  if (currentTime - createdAt >= MAX_TRIP_AGE_MS) {
    invalidTime('本机离线行程已过期（超过创建后 24 小时），不能恢复旧进度，请重新开始', 'OFFLINE_TRIP_EXPIRED');
  }
  return trip;
}

function readMode(wxApi) {
  try { return wxApi.getStorageSync(MODE_KEY) === 'online' ? 'online' : 'offline'; }
  catch (_) { return 'offline'; }
}

function saveMode(wxApi, mode) {
  try { wxApi.setStorageSync(MODE_KEY, mode); return true; } catch (_) { return false; }
}

function readTrip(wxApi, now = Date.now()) {
  try {
    const saved = wxApi.getStorageSync(TRIP_KEY);
    if (!saved) return { status: 'empty' };
    if (saved.version !== 1 || typeof saved.savedAt !== 'number' || !Number.isFinite(saved.savedAt)
      || !Array.isArray(saved.reminderKeys)
      || saved.reminderKeys.length > 64 || saved.reminderKeys.some((key) => typeof key !== 'string')) {
      throw new Error('本地记录结构不完整');
    }
    const trip = validateRecoveryTrip(saved.trip, { now, savedAt: saved.savedAt });
    return { status: 'saved', saved: { ...saved, trip } };
  } catch (error) {
    return { status: 'invalid', message: `离线行程无法恢复：${error.message || '本机存储不可用'}。请先保留诊断日志，再清除本机行程记录。` };
  }
}

function saveTrip(wxApi, trip, reminderKeys, now = Date.now()) {
  try {
    const savedAt = typeof now === 'function' ? now() : now;
    const verified = validateRecoveryTrip(trip, { now: savedAt, savedAt });
    wxApi.setStorageSync(TRIP_KEY, {
      version: 1, trip: verified, reminderKeys: [...new Set(reminderKeys)].slice(-64), savedAt
    });
    return { ok: true };
  } catch (error) {
    if (error.code === 'OFFLINE_TRIP_EXPIRED' || error.code === 'INVALID_OFFLINE_TRIP_TIME') {
      return { ok: false, message: `离线行程未能保存：${error.message}。原记录保留，继续保存不会延长恢复期限。` };
    }
    return { ok: false, message: '离线行程未能保存到手机；本次仍可人工操作，重新进入可能丢失进度或重复提醒。' };
  }
}

function clearTrip(wxApi) {
  try { wxApi.removeStorageSync(TRIP_KEY); return true; } catch (_) { return false; }
}

module.exports = { TRIP_KEY, MODE_KEY, MAX_TRIP_AGE_MS, CLOCK_SKEW_MS,
  readMode, saveMode, readTrip, saveTrip, clearTrip, validateRecoveryTrip };

},
"miniprogram/utils/location-health.js":function(module,exports,require){
// Foreground-only health tracking. This module keeps no coordinates, starts no
// timers, and makes no wx calls; the page owns lifecycle and in-app reminders.
const LOCATION_HEALTH_CONFIG = Object.freeze({
  maxAccuracyMeters: 120,
  badSamples: 3,
  goodSamples: 3,
  cooldownMs: 120000,
  callbackTimeoutMs: 15000,
  watchdogIntervalMs: 1000
});

function validAccuracy(value) {
  return typeof value === 'number' && Number.isFinite(value) && value >= 0;
}

function assessLocationQuality(sample, config = LOCATION_HEALTH_CONFIG) {
  const accuracy = validAccuracy(sample?.accuracy) ? sample.accuracy : null;
  const horizontal = sample?.horizontalAccuracy;
  const horizontalPresent = horizontal !== undefined && horizontal !== null;
  const stable = accuracy !== null && accuracy <= config.maxAccuracyMeters
    && (!horizontalPresent || (validAccuracy(horizontal) && horizontal <= config.maxAccuracyMeters))
    // The existing route-quality judgment can reject an otherwise precise fix.
    && sample?.stable !== false;
  return { accuracy, stable };
}

function createLocationHealth({ now = Date.now, config = LOCATION_HEALTH_CONFIG } = {}) {
  const settings = { ...LOCATION_HEALTH_CONFIG, ...config };
  let active = false;
  let state = 'paused';
  let accuracy = null;
  let lowCount = 0;
  let goodCount = 0;
  let lastReceivedAt = null;
  let callbackInterrupted = false;
  let episode = false;
  let lastDegradedState = null;
  let alertConsumed = false;
  let lastAlertAt = null;
  let pendingAlert = null;

  function snapshot() {
    return { state, unstable: active && episode, accuracy, lowCount, goodCount };
  }

  function enterDegraded(nextState) {
    if (!episode) {
      episode = true;
      alertConsumed = lastAlertAt !== null && now() - lastAlertAt < settings.cooldownMs;
    }
    state = nextState;
    lastDegradedState = nextState;
  }

  function start() {
    if (active) return snapshot();
    active = true;
    state = episode ? lastDegradedState : 'waiting';
    accuracy = null;
    lowCount = 0;
    goodCount = 0;
    lastReceivedAt = now();
    callbackInterrupted = false;
    return snapshot();
  }

  function stop() {
    active = false;
    state = 'paused';
    accuracy = null;
    lowCount = 0;
    goodCount = 0;
    lastReceivedAt = null;
    callbackInterrupted = false;
    return snapshot();
  }

  function sample(value) {
    if (!active) return snapshot();
    // Detect a missed watchdog tick before accepting a delayed callback.
    checkTimeout();
    callbackInterrupted = false;
    lastReceivedAt = now();
    const quality = assessLocationQuality(value, settings);
    accuracy = quality.accuracy;
    if (!quality.stable) {
      goodCount = 0;
      lowCount = Math.min(settings.badSamples, lowCount + 1);
      if (lowCount >= settings.badSamples) enterDegraded('unstable');
    } else {
      lowCount = 0;
      goodCount = Math.min(settings.goodSamples, goodCount + 1);
      if (!episode || goodCount >= settings.goodSamples) {
        cancelAlert();
        state = 'normal';
        episode = false;
        lastDegradedState = null;
        alertConsumed = false;
      }
    }
    return snapshot();
  }

  function checkTimeout() {
    if (!active || now() - lastReceivedAt < settings.callbackTimeoutMs) return snapshot();
    if (!callbackInterrupted) {
      callbackInterrupted = true;
      lowCount = 0;
      goodCount = 0;
      accuracy = null;
      enterDegraded('interrupted');
    }
    return snapshot();
  }

  function takeAlert({ deferCommit = false } = {}) {
    // Interruption has its own persistent message; this modal is for a streak
    // of poor fixes. Consume cooldown-suppressed episodes so no late popup fires.
    if (!active || state !== 'unstable' || !episode || alertConsumed) return false;
    alertConsumed = true;
    const currentTime = now();
    if (lastAlertAt !== null && currentTime - lastAlertAt < settings.cooldownMs) return false;
    if (deferCommit) pendingAlert = { previousAlertAt: lastAlertAt };
    lastAlertAt = currentTime;
    return true;
  }

  function confirmAlert() {
    if (!pendingAlert) return;
    lastAlertAt = now();
    pendingAlert = null;
  }

  function cancelAlert() {
    if (!pendingAlert) return;
    lastAlertAt = pendingAlert.previousAlertAt;
    pendingAlert = null;
    alertConsumed = false;
  }

  return { start, stop, sample, checkTimeout, takeAlert, confirmAlert, cancelAlert, snapshot };
}

module.exports = { LOCATION_HEALTH_CONFIG, assessLocationQuality, createLocationHealth };

},
"miniprogram/utils/reminders.js":function(module,exports,require){
// Pure decision. Persist alert.key only after the modal has actually rendered.
// Low-confidence and normal warnings share a stop key; arrival has a separate final key.
function decideReminder(trip, keys = [], options = {}) {
  if (!trip || !trip.id || !Array.isArray(trip.route) || trip.route.length < 2) return null;
  if (!Number.isInteger(trip.currentIndex) || trip.currentIndex < 0 || trip.currentIndex >= trip.route.length) return null;
  const station = trip.route[trip.currentIndex];
  const target = trip.route[trip.route.length - 1];
  if (!station || !station.id || !target) return null;
  const arrival = trip.status === 'arrived';
  const lowConfidence = options.lowConfidence === true && trip.status === 'active'
    && Number.isInteger(trip.stopsRemaining) && trip.stopsRemaining >= 0
    && Number.isInteger(trip.remindBefore) && trip.stopsRemaining <= trip.remindBefore + 1;
  if (!arrival && !(trip.status === 'active' && (trip.shouldRemind === true || lowConfidence))) return null;
  const key = JSON.stringify([String(trip.id), String(station.id), arrival ? 'arrived' : 'warning']);
  if (Array.isArray(keys) && keys.includes(key)) return null;
  const kind = arrival ? 'arrival' : lowConfidence ? 'low-confidence' : 'approaching';
  return {
    key,
    kind,
    title: arrival ? '到站啦，请确认下车站' : lowConfidence ? '定位不稳定，请提前准备' : '即将到站，请准备下车',
    message: arrival
      ? `行程记录已到达 ${target.name}。请结合车厢广播和站牌确认。`
      : `目标 ${target.name}，按当前行程记录还剩 ${trip.stopsRemaining} 站。${lowConfidence ? '请留意车厢广播，必要时人工校正。' : '请结合站牌确认实际位置。'}`
  };
}

function createEffects(wxApi, onStatus = () => {}) {
  let audio = null;
  let generation = 0;
  let disposed = false;
  let status = { sound: 'disabled', vibration: 'disabled', message: '' };

  function publish() {
    const failures = [];
    if (status.sound === 'unavailable' || status.sound === 'failed') failures.push('提示音不可用');
    if (status.vibration === 'unavailable' || status.vibration === 'failed') failures.push('震动不可用');
    if (failures.length) status.message = `${failures.join('、')}，请查看弹窗。`;
    const snapshot = Object.assign({}, status);
    onStatus(snapshot);
    return snapshot;
  }

  function stop() {
    generation += 1;
    const previous = audio;
    audio = null;
    if (previous) {
      try { if (typeof previous.stop === 'function') previous.stop(); } catch (_) { /* Popup stays usable. */ }
      try { if (typeof previous.destroy === 'function') previous.destroy(); } catch (_) { /* Native API unavailable. */ }
    }
  }

  function play(preferences = {}) {
    stop();
    const currentGeneration = generation;
    status = { sound: 'disabled', vibration: 'disabled', message: '' };
    if (disposed) return Object.assign({}, status);
    if (preferences.silent) {
      status.message = '静音模式：仅显示弹窗。';
      return publish();
    }
    if (preferences.sound === true) {
      if (!wxApi || typeof wxApi.createInnerAudioContext !== 'function') status.sound = 'unavailable';
      else {
        try {
          audio = wxApi.createInnerAudioContext();
          if (!audio || typeof audio.play !== 'function') throw new Error('Audio API unavailable');
          audio.autoplay = false;
          audio.loop = false;
          audio.obeyMuteSwitch = true;
          audio.volume = 0.45;
          audio.src = '/assets/arrival.wav';
          status.sound = 'requested';
          if (typeof audio.onError === 'function') audio.onError(() => {
            if (currentGeneration !== generation || disposed) return;
            status.sound = 'failed';
            publish();
          });
          if (typeof audio.onPlay === 'function') audio.onPlay(() => {
            if (currentGeneration !== generation || disposed) return;
            status.sound = 'playing';
            publish();
          });
          if (typeof audio.onEnded === 'function') audio.onEnded(() => {
            if (currentGeneration !== generation || disposed) return;
            status.sound = 'completed';
            publish();
          });
          audio.play();
        } catch (_) {
          status.sound = 'failed';
        }
      }
    }
    if (preferences.vibration === true) {
      if (!wxApi || typeof wxApi.vibrateShort !== 'function') status.vibration = 'unavailable';
      else {
        status.vibration = 'requested';
        try {
          wxApi.vibrateShort({
            type: 'light',
            success() {
              if (currentGeneration !== generation || disposed) return;
              status.vibration = 'completed';
              publish();
            },
            fail() {
              if (currentGeneration !== generation || disposed) return;
              status.vibration = 'failed';
              publish();
            }
          });
        } catch (_) { status.vibration = 'failed'; }
      }
    }
    if (!status.message) status.message = preferences.sound === true
      ? '提示音受设备音量、静音开关和微信能力影响，请以弹窗为准。'
      : '请查看弹窗确认站点。';
    return publish();
  }

  function dispose() { stop(); disposed = true; }
  return { play, stop, dispose };
}

module.exports = { decideReminder, createEffects };

}
};
const cache={};
function require(id){if(cache[id])return cache[id].exports;if(!modules[id])throw new Error('Unknown module '+id);const module=cache[id]={exports:{}};modules[id](module,module.exports,require);return module.exports;}
global.DaozhanCore=Object.freeze({offlineTrips:require("miniprogram/utils/offline-trips.js"),fieldStorage:require("miniprogram/utils/field-storage.js"),locationHealth:require("miniprogram/utils/location-health.js"),reminders:require("miniprogram/utils/reminders.js")});
})(typeof window==='undefined'?globalThis:window);
